# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpu-pod-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-pod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gpu-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gpu-pod
    spec:      
      containers:      
        - name: ubuntu
          image: ubuntu:latest
          command:
            - sleep
            - infinity              
      imagePullPolicy: Always
      resources:
        requests:
          cpu: 2000m
          memory: 9Gi
          nvidia.com/gpu: 1
        limits:
          cpu: 4000m
          memory: 9Gi
          nvidia.com/gpu: 1
      name: gpu-pod
        #ports:
        #- containerPort: 11434
        #  name: frontend
        #  protocol: TCP
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /data
          name: gpu-pod-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: gpu-pod-data
          persistentVolumeClaim:
          claimName: gpu-pod-data
---
# Service gpu-pod
apiVersion: v1
kind: Service
metadata:
  name: gpu-pod
  labels:
    app: gpu-pod
spec:
  ClusterIP: None
  selector:
    app: gpu-pod
  ports:
    - name: ssh
      port: 22
      targetPort: 22